export enum AppRoute {
  HOME = 'home',
  NETWORK = 'network',
  EVENTS = 'events',
  MESSAGING = 'messaging',
  NOTIFICATIONS = 'notifications',
  PROFILE = 'profile',
  SETTINGS = 'settings',
  SUPERVISION = 'supervision',
  EVENT_DETAIL = 'event-detail',
  HELP = 'help',
  ONBOARDING = 'onboarding',
  GUARDIAN = 'guardian',
  SENT = 'sent',
  EXPLORE = 'explore',
  GROUPS = 'groups',
  TEAMS = 'teams',
  SAVED = 'saved',
  CONNECTIONS = 'connections',
}
