export enum RelationshipStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
  BLOCKED = 'BLOCKED',
}

export enum GuardianErrorCode {
  INVITE_CODE_INVALID = 'INVITE_CODE_INVALID',
  CHILD_SETUP_INCOMPLETE = 'GUARDIAN_REQUEST_CHILD_SETUP_INCOMPLETE',
  GUARDIAN_SETUP_INCOMPLETE = 'GUARDIAN_REQUEST_GUARDIAN_SETUP_INCOMPLETE',
  ALREADY_LINKED = 'GUARDIAN_ALREADY_LINKED',
}
