[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/v1/*"
  to = "https://reposeful-kareen-controllingly.ngrok-free.dev/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
