services:
  - type: web
    name: my-hockey-network-web
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /v1/*
        destination: https://reposeful-kareen-controllingly.ngrok-free.dev/v1/*
      - type: rewrite
        source: /*
        destination: /index.html
