export enum HttpHeader {
  ACCEPT = 'Accept',
  ACCEPT_LANGUAGE = 'Accept-Language',
  CONTENT_TYPE = 'Content-Type',
  AUTHORIZATION = 'Authorization',
  X_CLIENT_TYPE = 'X-Client-Type',
  X_CSRF_TOKEN = 'X-CSRF-Token',
  X_XSRF_TOKEN = 'X-XSRF-Token',
  CSRF_TOKEN = 'csrf-token',
  MHN_AT = 'mhn_at',
  MHN_CSRF = 'mhn_csrf',
  X_REFRESH_TOKEN = 'X-Refresh-Token',
  X_ACCESS_TOKEN = 'x-access-token',
  X_ACTING_FOR = 'X-Acting-For',
}
