export enum PermissionControlKey {
  VIEW_FEED = 'VIEW_FEED',
  CREATE_POST = 'CREATE_POST',
  REACT_TO_POSTS = 'REACT_TO_POSTS',
  COMMENT_ON_POSTS = 'COMMENT_ON_POSTS',
  SHARE_POSTS = 'SHARE_POSTS',
  FOLLOW_OTHERS = 'FOLLOW_OTHERS',
  SEND_MESSAGES = 'SEND_MESSAGES',
  CREATE_GROUP_CHATS = 'CREATE_GROUP_CHATS',
}
