export enum SupervisionControlKeyEnum {
  // Feed Controls
  VIEW_FEED = 'VIEW_FEED',
  CREATE_POST = 'CREATE_POST',
  COMMENT_ON_POSTS = 'COMMENT_ON_POSTS',
  REACT_TO_POSTS = 'REACT_TO_POSTS',
  SHARE_POSTS = 'SHARE_POSTS',

  // Network Controls
  FOLLOW_OTHERS = 'FOLLOW_OTHERS',
  WHO_CAN_FOLLOW = 'WHO_CAN_FOLLOW',
  WHO_CAN_SEND_CONNECTION_REQUESTS = 'WHO_CAN_SEND_CONNECTION_REQUESTS',
  ACCEPT_CONNECTIONS = 'ACCEPT_CONNECTIONS',

  // Messaging Controls
  SEND_MESSAGES = 'SEND_MESSAGES',
  RECEIVE_MESSAGES = 'RECEIVE_MESSAGES',
  CREATE_GROUP_CHATS = 'CREATE_GROUP_CHATS',
  WHO_CAN_MESSAGE_THEM = 'WHO_CAN_MESSAGE_THEM',

  // Approval / Notification Controls
  REQUIRE_APPROVAL_ADULT_CONTACT = 'REQUIRE_APPROVAL_ADULT_CONTACT',
  REQUIRE_APPROVAL_CONNECTIONS = 'REQUIRE_APPROVAL_CONNECTIONS',
  REQUIRE_APPROVAL_TEAM_INVITES = 'REQUIRE_APPROVAL_TEAM_INVITES',
  REQUIRE_APPROVAL_MEDIA = 'REQUIRE_APPROVAL_MEDIA',
}

export const PermissionControlKey = SupervisionControlKeyEnum;
export type PermissionControlKey = SupervisionControlKeyEnum;
