export enum QueryKeys {
  AUTH_ME = 'auth:me',
  SUPERVISION_PERMISSIONS = 'supervision:permissions',
  SUPERVISION_DATA = 'supervision:data',
  SUPERVISION_LOGS = 'supervision:logs',
  PENDING_APPROVALS = 'approvals:pending',
  PENDING_GUARDIAN_REQUESTS = 'guardian:requests:pending',
  PENDING_GUARDIAN_INVITES = 'guardian:invites:pending',
  NETWORK_RELATIONSHIPS = 'network:relationships',
  PEOPLE_YOU_MAY_KNOW = 'network:people-you-may-know',
  FEED_POSTS = 'feed:posts',
  POST_COMMENTS = 'posts:comments',
  USER_PROFILE = 'profile:user',
  USER_POSTS = 'profile:posts',
  REFERENCE_DATA = 'reference:data',
  SETTINGS_BLOCKED_USERS = 'settings:blocked-users',
  SETTINGS_NOTIFICATIONS = 'settings:notifications',
}
